const milestones = [
  'Trip Started','Arrived at Loading Point','Loading Started','Loading Completed — Waiting for Document','Vehicle Departed',
  'Advance Payment Request','Final Payment Calculated','Driver Accepted Final Payment','Trip Closed'
];
const branches = ['Delhi','Mumbai','Bengaluru'];
const roles = [['admin','Admin'],['branch_manager','Branch Manager'],['operations','Operations'],['tracking','Tracking'],['driver','Driver']];
const lanes = [
  {id:'LN-DEL-MUM',from:'Delhi',to:'Mumbai',km:1410,tat:42,rate:58000},
  {id:'LN-MUM-BLR',from:'Mumbai',to:'Bengaluru',km:980,tat:30,rate:43000},
  {id:'LN-BLR-DEL',from:'Bengaluru',to:'Delhi',km:2150,tat:66,rate:82000}
];
const issueTypes = {
  Breakdown: {severity:'Critical', route:'Maintenance + Ops', ticket:true},
  Accident: {severity:'Critical', route:'Ops + Safety + Mgmt', ticket:false},
  'Urea needed': {severity:'Medium', route:'Ops team', ticket:false},
  'Fuel issue': {severity:'Medium', route:'Ops + Accounts', ticket:false},
  Payment: {severity:'Medium', route:'Accounts', ticket:false},
  'Unloading charges': {severity:'Action', route:'Accounts + Branch', ticket:false},
  'Route refusal': {severity:'Escalated', route:'Ops + Mgmt', ticket:false}
};
let state = {
  role:'admin', branch:'Delhi', view:'control', note:'Ready: demo-safe GPS, SMS, BPCL and LR/Bilty stubs are active.', audit:[],
  vehicles:[
    {registration:'DL 01 AB 4582',type:'12ft',branch:'Delhi',bucket:'Loading',active:true,idleHours:1.4},
    {registration:'MH 04 CX 9011',type:'container',branch:'Mumbai',bucket:'In-Transit',active:true,idleHours:0.2},
    {registration:'KA 05 MC 7720',type:'10ft',branch:'Bengaluru',bucket:'Available',active:true,idleHours:5.1},
    {registration:'DL 08 QW 1129',type:'9ft',branch:'Delhi',bucket:'Breakdown',active:true,idleHours:2.8}
  ],
  drivers:[
    {name:'Ramesh Kumar',phone:'+91 98765 43210',branch:'Delhi',expiry:'2026-07-28',rating:87},
    {name:'Iqbal Khan',phone:'+91 99887 77665',branch:'Mumbai',expiry:'2027-02-14',rating:92},
    {name:'Manoj S',phone:'+91 91234 56789',branch:'Bengaluru',expiry:'2026-08-02',rating:79}
  ],
  trips:[
    {id:'TRP-0001',customer:'Century Retail',lane:lanes[0],vehicle:'DL 01 AB 4582',driver:'Ramesh Kumar',branch:'Delhi',step:3,eta:'Today 18:40',delayed:false,advance:'pending',payment:'open',pod:'not uploaded',cancelled:false},
    {id:'TRP-0002',customer:'Northstar Foods',lane:lanes[1],vehicle:'MH 04 CX 9011',driver:'Iqbal Khan',branch:'Mumbai',step:5,eta:'Tomorrow 09:20',delayed:true,advance:'requested',payment:'open',pod:'not uploaded',cancelled:false},
    {id:'TRP-0003',customer:'Metro Components',lane:lanes[2],vehicle:'KA 05 MC 7720',driver:'Manoj S',branch:'Bengaluru',step:8,eta:'Closed',delayed:false,advance:'settled',payment:'settled',pod:'uploaded',cancelled:false}
  ],
  issues:[{id:'ISS-001',tripId:'TRP-0001',type:'Breakdown',severity:'Critical',route:'Maintenance + Ops',status:'Open',sla:'01:20'}],
  tickets:[{id:'TCK-001',tripId:'TRP-0001',vehicle:'DL 08 QW 1129',statusIndex:1,tech:'Tech assigned'}],
  fuel:[{id:'FUEL-001',vehicle:'MH 04 CX 9011',amount:6500,date:'2026-07-10',note:'Demo BPCL stub'}],
  expenses:[{tripId:'TRP-0002',category:'fuel',amount:6500},{tripId:'TRP-0001',category:'advance',amount:10000}],
  loginAttempts:0, lockedUntil:null, currentUser:'Demo Admin',
  customers:[{name:'Century Retail',branch:'Delhi',active:true},{name:'Northstar Foods',branch:'Mumbai',active:true}],
  masterBranches:[{name:'Delhi',active:true},{name:'Mumbai',active:true},{name:'Bengaluru',active:true}],
  gps:[{deviceId:'WE-001',vehicleId:'DL 01 AB 4582',lat:28.6139,lng:77.2090,speed:32,ignition:true,timestamp:'live'}],
  geofences:[{name:'Delhi loading point',radius:'200m'}]
};
const nav = [['auth','🔐','Auth'],['control','📊','Control Tower'],['trips','📋','Trips'],['fleet','🚚','Fleet Masters'],['driver','👤','Driver App'],['finance','⛽','Finance'],['maintenance','🔧','Maintenance'],['automation','⚙️','Edge Automation'],['audit','🧾','Audit Log']];
const ticketStatuses = ['Reported','Assigned','Travelling','Work Started','Work Done','Roadworthy','Closed'];
const visibleTrips = () => state.role === 'admin' ? state.trips : state.trips.filter(t => t.branch === state.branch || state.role === 'driver');
const visibleVehicles = () => state.role === 'admin' ? state.vehicles : state.vehicles.filter(v => v.branch === state.branch || state.role === 'driver');
const money = n => '₹' + Number(n || 0).toLocaleString('en-IN');
const today = () => new Date().toISOString().slice(0,10);
function log(action){ state.audit.unshift({time:new Date().toLocaleTimeString(), actor:state.role, action}); state.note = action; }
function setView(view){ state.view=view; render(); }
function setRole(role){ state.role=role; render(); }
function setBranch(branch){ state.branch=branch; render(); }
function bucketForStep(step){ return step < 2 ? 'Loading' : step < 5 ? 'Loading' : step < 8 ? 'In-Transit' : 'Available'; }
function updateVehicleBucket(reg,bucket){ state.vehicles = state.vehicles.map(v => v.registration === reg ? {...v,bucket,idleHours:bucket==='Available'?0:v.idleHours} : v); }
function createTrip(){ const id=`TRP-${String(state.trips.length+1).padStart(4,'0')}`; const lane=lanes[0]; state.trips=[{id,customer:'Demo Customer',lane,vehicle:'DL 01 AB 4582',driver:'Ramesh Kumar',branch:'Delhi',step:0,eta:'Calculating',delayed:false,advance:'not requested',payment:'open',pod:'not uploaded',cancelled:false},...state.trips]; updateVehicleBucket('DL 01 AB 4582','Loading'); log(`${id} created. Lane TAT ${lane.tat}h and rate ${money(lane.rate)} applied; no LR/Bilty generated.`); render(); }
function advanceTrip(id){ state.trips = state.trips.map(t => { if(t.id!==id || t.cancelled) return t; const step=Math.min(t.step+1,8); updateVehicleBucket(t.vehicle, bucketForStep(step)); return {...t,step,eta:step===8?'Closed':t.eta,payment:step===8?'settled':t.payment,advance:step===8?'settled':t.advance}; }); log(`${id} moved to next milestone; timestamp, branch bucket, Control Tower and notification stub updated.`); render(); }
function cancelTrip(id){ state.trips = state.trips.map(t => t.id===id ? {...t,cancelled:true,eta:'Cancelled'} : t); const trip=state.trips.find(t=>t.id===id); if(trip) updateVehicleBucket(trip.vehicle,'Available'); log(`${id} cancelled by ${state.role}; reason logged and vehicle reset to Available.`); render(); }
function requestAdvance(id){ state.trips = state.trips.map(t => t.id===id ? {...t,advance:'requested',step:Math.max(t.step,5)} : t); log(`${id} advance payment request raised by driver; Branch Manager notified.`); render(); }
function approveAdvance(id){ state.trips = state.trips.map(t => t.id===id ? {...t,advance:'approved',step:6} : t); log(`${id} advance approved; driver can proceed to final payment calculation.`); render(); }
function rejectAdvance(id){ state.trips = state.trips.map(t => t.id===id ? {...t,advance:'rejected - re-raise allowed'} : t); log(`${id} advance rejected with demo reason; driver notified and can re-raise.`); render(); }
function calculateFinal(id){ state.trips = state.trips.map(t => t.id===id ? {...t,payment:'calculated',step:7} : t); log(`${id} final payment calculated by Branch Manager.`); render(); }
function driverPayment(id,accepted){ state.trips = state.trips.map(t => t.id===id ? {...t,payment:accepted?'settled':'driver rejected - needs notes',step:accepted?8:7,advance:accepted?'settled':t.advance,eta:accepted?'Closed':t.eta} : t); const trip=state.trips.find(t=>t.id===id); if(accepted && trip) updateVehicleBucket(trip.vehicle,'Available'); log(accepted ? `${id} final payment accepted; trip closed and vehicle available.` : `${id} final payment rejected with driver note; sent back to Branch Manager.`); render(); }
function markAvailable(reg){ updateVehicleBucket(reg,'Available'); log(`${reg} marked Empty/Available by driver fallback.`); render(); }
function deactivateVehicle(reg){ const active=state.trips.some(t=>t.vehicle===reg && !t.cancelled && t.step<8); if(active){ log(`${reg} cannot be deactivated because it has an active trip.`); } else { state.vehicles=state.vehicles.map(v=>v.registration===reg?{...v,active:false}:v); log(`${reg} deactivated; history preserved.`); } render(); }
function addVehicle(){ const registration=`DEMO ${String(state.vehicles.length+1).padStart(2,'0')}`; state.vehicles=[...state.vehicles,{registration,type:'10ft',branch:state.branch,bucket:'Available',active:true,idleHours:0}]; log(`${registration} added to ${state.branch} as Available.`); render(); }
function addDriver(){ const name=`Demo Driver ${state.drivers.length+1}`; state.drivers=[...state.drivers,{name,phone:'+91 90000 00000',branch:state.branch,expiry:'2026-08-05',rating:80}]; log(`${name} added; license expiry flag shown if under 30 days.`); render(); }
function raiseIssue(type){ const trip=visibleTrips()[0] || state.trips[0]; const meta=issueTypes[type]; const id=`ISS-${String(state.issues.length+1).padStart(3,'0')}`; state.issues=[{id,tripId:trip.id,type,severity:meta.severity,route:meta.route,status:'Open',sla:'00:00'},...state.issues]; if(type==='Route refusal'){ state.drivers=state.drivers.map(d=>d.name===trip.driver?{...d,rating:Math.max(0,d.rating-5)}:d); }
  if(meta.ticket){ const ticketId=`TCK-${String(state.tickets.length+1).padStart(3,'0')}`; state.tickets=[{id:ticketId,tripId:trip.id,vehicle:trip.vehicle,statusIndex:0,tech:'Unassigned'},...state.tickets]; updateVehicleBucket(trip.vehicle,'Breakdown'); }
  log(`${type} issue raised for ${trip.id}; routed to ${meta.route}${meta.ticket?' and ticket auto-created':''}.`); render(); }
function uploadPod(id){ state.trips=state.trips.map(t=>t.id===id?{...t,pod:'uploaded'}:t); log(`${id} POD uploaded; Ops notified and ageing clock stopped.`); render(); }
function addFuel(){ const vehicle=document.querySelector('#fuelVehicle')?.value || 'DL 01 AB 4582'; const amount=Number(document.querySelector('#fuelAmount')?.value || 2500); const note=document.querySelector('#fuelNote')?.value || 'Manual BPCL stub'; state.fuel=[{id:`FUEL-${String(state.fuel.length+1).padStart(3,'0')}`,vehicle,amount,date:today(),note},...state.fuel]; state.expenses=[...state.expenses,{tripId:visibleTrips()[0]?.id || 'TRP-0001',category:'fuel',amount}]; log(`Fuel transaction created manually for ${vehicle}; no OTP/payment API called.`); render(); }
function ticketNext(id){ state.tickets=state.tickets.map(t=>{ if(t.id!==id) return t; const statusIndex=Math.min(t.statusIndex+1,ticketStatuses.length-1); if(ticketStatuses[statusIndex]==='Roadworthy') updateVehicleBucket(t.vehicle,'In-Transit'); if(ticketStatuses[statusIndex]==='Closed') updateVehicleBucket(t.vehicle,'Available'); return {...t,statusIndex,tech:t.tech==='Unassigned'?'Tech assigned':t.tech}; }); log(`${id} moved to next maintenance status; driver notified.`); render(); }
function exportCsv(){ const rows=['tripId,category,amount',...state.expenses.map(e=>`${e.tripId},${e.category},${e.amount}`)]; log(`CSV export prepared: ${rows.length-1} expense rows.`); alert(rows.join('\n')); }
function loginDemo(success=true){ if(state.lockedUntil){ log('Account locked for 15 minutes after 5 failed attempts.'); render(); return; } if(success){ state.loginAttempts=0; state.currentUser=state.role==='driver'?'Demo Driver':'Demo Staff'; log(`${state.currentUser} logged in and routed to ${state.role} dashboard.`); } else { state.loginAttempts += 1; if(state.loginAttempts>=5){ state.lockedUntil='15 minutes'; log('Login failed 5 times: account locked for 15 minutes.'); } else { log(`Login failed. Attempts: ${state.loginAttempts}/5.`); } } render(); }
function forgotPassword(){ log('Forgot password stub: admin manually resets password from user list.'); render(); }
function logout(){ state.currentUser='Logged out'; log('User logged out.'); render(); }
function addCustomer(){ const name=`Demo Customer ${state.customers.length+1}`; state.customers=[...state.customers,{name,branch:state.branch,active:true}]; log(`${name} added under ${state.branch}; deactivate preserves history.`); render(); }
function deactivateCustomer(name){ state.customers=state.customers.map(c=>c.name===name?{...c,active:false}:c); log(`${name} deactivated; history preserved.`); render(); }
function addLane(){ const id=`LN-DEMO-${state.geofences.length+1}`; lanes.push({id,from:state.branch,to:'Demo Destination',km:500,tat:18,rate:22000}); log(`${id} lane added with planned TAT and standard rate.`); render(); }
function simulateGps(){ const ping={deviceId:'WE-001',vehicleId:'DL 01 AB 4582',lat:28.6139+Math.random()/100,lng:77.2090+Math.random()/100,speed:42,ignition:true,timestamp:new Date().toLocaleTimeString()}; state.gps=[ping,...state.gps].slice(0,5); state.geofences=[...state.geofences,{name:`Auto geofence ${state.geofences.length+1}`,radius:'200m'}]; log('WheelsEye simulator ping received; ETA/delay recalculated and geofence auto-created near known stop.'); render(); }
function runIdleTimer(){ state.vehicles=state.vehicles.map(v=>v.bucket==='Available'?{...v,idleHours:4.5}:v); log('Idle timer ran: vehicles stationary over 4h are flagged and sent to Control Tower.'); render(); }
function triggerPodAgeing(){ state.issues=[{id:`ISS-${String(state.issues.length+1).padStart(3,'0')}`,tripId:'TRP-0002',type:'POD ageing',severity:'Accounts',route:'Accounts alert',status:'Open',sla:'48h+'},...state.issues]; log('POD ageing alert fired for unuploaded/unpaid POD over 48h.'); render(); }
function markGpsOff(){ state.issues=[{id:`ISS-${String(state.issues.length+1).padStart(3,'0')}`,tripId:'TRP-0002',type:'GPS off',severity:'Ops',route:'Ops flagged',status:'Open',sla:'1h+'},...state.issues]; log('GPS off alert created: no ping for more than 1 hour.'); render(); }
function badge(text,warn=false){ return `<span class="badge ${warn?'warning':''}">${text}</span>`; }
function card(title, body, action=''){ return `<section class="card"><div class="card-head"><h2>${title}</h2>${action}</div>${body}</section>`; }
function render(){ const title=nav.find(n=>n[0]===state.view)[2]; document.body.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="big">🚚</span><div><strong>TransportOS</strong><span>Century Cargo demo</span></div></div><nav>${nav.map(n=>`<button class="${state.view===n[0]?'active':''}" onclick="setView('${n[0]}')"><span>${n[1]}</span>${n[2]}</button>`).join('')}</nav><div class="demo-note">Localhost Phase 0: GPS, SMS, BPCL and GST flows are demo-safe stubs.</div></aside><main><header class="topbar"><div><p class="eyebrow">Live demo workspace</p><h1>${title}</h1></div><div class="controls"><select onchange="setRole(this.value)">${roles.map(r=>`<option value="${r[0]}" ${state.role===r[0]?'selected':''}>${r[1]}</option>`).join('')}</select><select onchange="setBranch(this.value)">${branches.map(b=>`<option ${state.branch===b?'selected':''}>${b}</option>`).join('')}</select></div></header><section class="notice">🔔 ${state.note}</section>${viewHtml()}</main></div>`; }
function viewHtml(){ return ({auth:authHtml,control:controlHtml,trips:tripsHtml,fleet:fleetHtml,driver:driverHtml,finance:financeHtml,maintenance:maintenanceHtml,automation:automationHtml,audit:auditHtml}[state.view])(); }
function authHtml(){ return `<div class="grid two">${card('Login / Forgot Password',`<div class="form-grid"><input placeholder="Staff email or driver phone" value="admin@century.demo"><input placeholder="Password" value="demo123"><button onclick="loginDemo(true)">Login</button><button class="secondary" onclick="loginDemo(false)">Simulate Failed Login</button><button class="secondary" onclick="forgotPassword()">Forgot Password</button><button class="danger" onclick="logout()">Logout</button></div><p class="muted">Current user: ${state.currentUser}. Failed attempts: ${state.loginAttempts}/5. Lock: ${state.lockedUntil || 'none'}.</p>`)}${card('RBAC routing',roles.map(r=>`<div class="row"><strong>${r[1]}</strong><span>${r[0]==='admin'?'All branches':r[0]==='driver'?'Own trips':'Own branch'}</span></div>`).join(''))}</div>`; }
function controlHtml(){ const vs=visibleVehicles(), ts=visibleTrips(); const k={fleet:vs.length,idle:vs.filter(v=>v.idleHours>4).length,alerts:state.issues.filter(i=>i.status==='Open').length+vs.filter(v=>v.idleHours>4||v.bucket==='Breakdown').length+ts.filter(t=>t.delayed).length,breakdowns:vs.filter(v=>v.bucket==='Breakdown').length}; const alerts=[...state.issues.map(i=>`${i.id}: ${i.type} routed to ${i.route}`),...vs.filter(v=>v.idleHours>4).map(v=>`${v.registration}: Idle ${v.idleHours}h, Branch Manager alerted`),...ts.filter(t=>t.delayed).map(t=>`${t.id}: Trip delayed vs ETA, Ops + Management alerted`),'GPS simulator polling every 30 seconds with WheelsEye-shaped JSON']; return `<div class="stack"><div class="kpi-grid">${[['Fleet count',k.fleet,'🚚'],['Idle > 4h',k.idle,'🚗'],['Active alerts',k.alerts,'🔔'],['Breakdowns',k.breakdowns,'🔧']].map(x=>`<article class="kpi"><div><span>${x[0]}</span><strong>${x[1]}</strong></div><b>${x[2]}</b></article>`).join('')}</div><div class="grid two">${card('Live alert feed',`<ul class="feed">${alerts.map(a=>`<li>⚠️ ${a}</li>`).join('')}</ul>`)}${card('Branch table',`<table><thead><tr><th>Branch</th><th>Fleet</th><th>Available</th><th>Breakdown</th></tr></thead><tbody>${branches.map(b=>`<tr><td>${b}</td><td>${vs.filter(v=>v.branch===b).length}</td><td>${vs.filter(v=>v.branch===b&&v.bucket==='Available').length}</td><td>${vs.filter(v=>v.branch===b&&v.bucket==='Breakdown').length}</td></tr>`).join('')}</tbody></table>`)}</div></div>`; }
function tripsHtml(){ const ts=visibleTrips(); return `<div class="stack">${card('Trip Creation','<p class="muted">Ops/Admin can create trips. Save creates only a Trip record; no LR/Bilty is generated at this stage.</p>',(state.role==='admin'||state.role==='operations')?'<button onclick="createTrip()">Create Trip</button>':'')}${card('Payment workflow helper','<p class="muted">Use Request Advance → Approve/Reject → Calculate Final → Driver Accept/Reject to demo steps 6–8.</p>')}<div class="kanban">${milestones.map((m,i)=>`<section class="lane"><h3>${i+1}. ${m}</h3>${ts.filter(t=>t.step===i&&!t.cancelled).map(tripCard).join('')}</section>`).join('')}</div>${card('Cancelled trips',ts.filter(t=>t.cancelled).map(t=>`<div class="row"><strong>${t.id}</strong><span>${t.vehicle} reset to Available</span></div>`).join('') || '<p class="muted">No cancelled trips.</p>')}</div>`; }
function tripCard(t){ return `<article class="trip-card"><strong>${t.id}</strong><span>${t.customer}</span><small>${t.lane.from} → ${t.lane.to} · ${t.vehicle}</small><small>Advance: ${t.advance} · Payment: ${t.payment} · POD: ${t.pod}</small><div class="actions"><button ${t.step===8?'disabled':''} onclick="advanceTrip('${t.id}')">Next milestone</button><button class="secondary" onclick="requestAdvance('${t.id}')">Request Advance</button><button class="secondary" onclick="approveAdvance('${t.id}')">Approve</button><button class="secondary" onclick="rejectAdvance('${t.id}')">Reject</button><button class="secondary" onclick="calculateFinal('${t.id}')">Calculate Final</button><button class="secondary" onclick="driverPayment('${t.id}',true)">Driver Accept</button><button class="secondary" onclick="driverPayment('${t.id}',false)">Driver Reject</button><button class="secondary" onclick="uploadPod('${t.id}')">Upload POD</button><button class="danger" onclick="cancelTrip('${t.id}')">Cancel</button></div></article>`; }
function fleetHtml(){ const vs=visibleVehicles(); return `<div class="grid three">${card('Vehicles',vs.map(v=>`<div class="row"><div><strong>${v.registration}</strong><span>${v.type} · ${v.branch} · ${v.active?'Active':'Inactive'}</span></div>${badge(v.bucket,v.idleHours>4)}<button onclick="markAvailable('${v.registration}')">Mark Empty/Available</button><button class="secondary" onclick="deactivateVehicle('${v.registration}')">Deactivate</button></div>`).join(''),'<button onclick="addVehicle()">Add Vehicle</button>')}${card('Drivers',state.drivers.map(d=>`<div class="row"><div><strong>${d.name}</strong><span>${d.phone} · ${d.branch} · Rating ${d.rating}</span></div>${new Date(d.expiry)<new Date('2026-08-09')?badge('License < 30d',true):''}</div>`).join(''),'<button onclick="addDriver()">Add Driver</button>')}${card('Lanes',lanes.map(l=>`<div class="row"><div><strong>${l.from} → ${l.to}</strong><span>${l.km} km · TAT ${l.tat}h · ${money(l.rate)}</span></div></div>`).join(''),'<button onclick="addLane()">Add Lane</button>')}${card('Branches',state.masterBranches.map(b=>`<div class="row"><strong>${b.name}</strong>${badge(b.active?'Active':'Inactive')}</div>`).join(''))}${card('Customers',state.customers.map(c=>`<div class="row"><div><strong>${c.name}</strong><span>${c.branch} · ${c.active?'Active':'Inactive'}</span></div><button class="secondary" onclick="deactivateCustomer('${c.name}')">Deactivate</button></div>`).join(''),'<button onclick="addCustomer()">Add Customer</button>')}</div>`; }
function driverHtml(){ const t=visibleTrips().find(x=>!x.cancelled) || state.trips[0]; return `<div class="phone-layout"><section class="phone"><div class="phone-bar"></div><h2>Driver Trip</h2><p>${t.id} · ${t.vehicle}</p><div class="progress">${milestones.map((m,i)=>`<div class="${i<=t.step?'done':''}">✅ ${m}</div>`).join('')}</div><button onclick="advanceTrip('${t.id}')">Tap next milestone</button><button class="secondary" onclick="requestAdvance('${t.id}')">Raise Advance Request</button><button class="secondary" onclick="uploadPod('${t.id}')">Upload POD</button><button class="secondary" onclick="markAvailable('${t.vehicle}')">Mark Empty/Available</button></section>${card('Issue Button',Object.keys(issueTypes).map(type=>`<div class="issue"><b>⚠️</b><div><strong>${type}</strong><span>${issueTypes[type].severity} · ${issueTypes[type].route}</span></div><button onclick="raiseIssue('${type}')">Raise</button></div>`).join(''))}${card('Open Issues',state.issues.map(i=>`<div class="row"><div><strong>${i.id} · ${i.type}</strong><span>${i.tripId} · ${i.route} · SLA ${i.sla}</span></div>${badge(i.status,true)}</div>`).join(''))}</div>`; }
function financeHtml(){ const ts=visibleTrips(); return `<div class="grid two">${card('Advance Payment Requests',ts.map(t=>`<div class="row"><div><strong>${t.id}</strong><span>${t.driver} · ${t.advance}</span></div><button onclick="approveAdvance('${t.id}')">Approve</button><button class="secondary" onclick="rejectAdvance('${t.id}')">Reject</button><button class="secondary" onclick="calculateFinal('${t.id}')">Add Note / Calculate Final</button></div>`).join(''))}${card('Fuel Transactions Stub','<div class="form-grid"><input id="fuelVehicle" placeholder="Vehicle" value="DL 01 AB 4582"><input id="fuelAmount" placeholder="Amount" value="2500"><input type="date"><input id="fuelNote" placeholder="Note" value="Manual BPCL stub"><button onclick="addFuel()">Add Fuel Transaction</button><button class="secondary" onclick="exportCsv()">Export CSV</button></div><p class="muted">No BPCL OTP or payment API call is made in demo scope.</p>'+state.fuel.map(f=>`<div class="row"><strong>${f.id}</strong><span>${f.vehicle} · ${money(f.amount)} · ${f.note}</span></div>`).join(''))}</div>`; }
function maintenanceHtml(){ return `<div class="stack">${card('Breakdown Ticket Board',state.tickets.map(t=>`<div class="row"><div><strong>${t.id} · ${t.vehicle}</strong><span>${t.tripId} · ${ticketStatuses[t.statusIndex]} · ${t.tech}</span></div><button onclick="ticketNext('${t.id}')">${t.statusIndex===0?'Assign Technician':'Mark Next Status'}</button></div>`).join('') || '<p class="muted">No tickets yet. Raise a Breakdown issue from Driver App.</p>')}${card('Workflow',`<div class="ticket-flow">${ticketStatuses.map((s,i)=>`<div class="${i<2?'active':''}">${s}</div>`).join('')}</div><p class="muted">Roadworthy resumes trip and Closed resets the vehicle bucket to Available.</p>`)}</div>`; }
function automationHtml(){ return `<div class="grid two">${card('WheelsEye GPS simulator',`<p class="muted">Same JSON shape: deviceId, vehicleId, lat, lng, speed, ignition, timestamp.</p><button onclick="simulateGps()">Simulate GPS Ping</button>${state.gps.map(g=>`<div class="row"><strong>${g.vehicleId}</strong><span>${g.deviceId} · ${g.lat.toFixed ? g.lat.toFixed(4) : g.lat}, ${g.lng.toFixed ? g.lng.toFixed(4) : g.lng} · ${g.speed} km/h · ${g.timestamp}</span></div>`).join('')}`)}${card('Background automations',`<div class="actions"><button onclick="runIdleTimer()">Run Idle Timer</button><button onclick="markGpsOff()">Create GPS Off Alert</button><button onclick="triggerPodAgeing()">Create POD Ageing Alert</button></div>${state.geofences.map(g=>`<div class="row"><strong>${g.name}</strong><span>Radius ${g.radius}</span></div>`).join('')}`)}${card('Spec coverage checklist', ['Auth lockout and forgot password stub','Branches, Vehicles, Drivers, Customers, Lanes masters','Trip lifecycle 9 steps, cancellation, payments','Branch buckets and idle timer','Driver issues, POD upload, route refusal rating deduction','Maintenance ticket board','Fuel transaction stub and CSV export','Control Tower alerts and KPI cards','GPS simulator, geofence, ETA/delay, audit log'].map(x=>`<div class="row"><strong>✅ ${x}</strong></div>`).join(''))}</div>`; }
function auditHtml(){ return card('Immutable audit trail',state.audit.map(a=>`<div class="row"><div><strong>${a.time} · ${a.actor}</strong><span>${a.action}</span></div></div>`).join('') || '<p class="muted">Click app actions to create audit events.</p>'); }
Object.assign(window,{setView,setRole,setBranch,createTrip,advanceTrip,cancelTrip,requestAdvance,approveAdvance,rejectAdvance,calculateFinal,driverPayment,markAvailable,deactivateVehicle,addVehicle,addDriver,raiseIssue,uploadPod,addFuel,ticketNext,exportCsv,loginDemo,forgotPassword,logout,addCustomer,deactivateCustomer,addLane,simulateGps,runIdleTimer,triggerPodAgeing,markGpsOff});
render();
